export const programmingSkills = [
  { label: 'Aiscript', value: 'aiscript' },
  { label: 'C', value: 'c' },
  { label: 'C#', value: 'cs' },
  { label: 'C++', value: 'cpp' },
  { label: 'Crystal', value: 'crystal' },
  { label: 'Clojure', value: 'clojure' },
  { label: 'Coffeescript', value: 'coffeescript' },
  { label: 'CSS', value: 'css' },
  { label: 'Dart', value: 'dart' },
  { label: 'Elixir', value: 'elixir' },
  { label: 'Forth', value: 'forth' },
  { label: 'Fortran', value: 'fortran' },
  { label: 'Go', value: 'go' },
  { label: 'Haxe', value: 'haxe' },
  { label: 'HTML', value: 'html' },
  { label: 'Java', value: 'java' },
  { label: 'Javascript', value: 'js' },
  { label: 'Kotlin', value: 'kotlin' },
  { label: 'Lua', value: 'lua' },
  { label: 'Nim(Nimrod)', value: 'nim' },
  { label: 'OCaml', value: 'ocaml' },
  { label: 'GNU Octave', value: 'octave' },
  { label: 'Perl', value: 'perl' },
  { label: 'PHP', value: 'php' },
  { label: 'TypeScript', value: 'ts' },
  { label: 'Processing', value: 'processing' },
  { label: 'Python', value: 'py' },
  { label: 'R', value: 'r' },
  { label: 'Ruby', value: 'ruby' },
  { label: 'Rust', value: 'rust' },
  { label: 'Scala', value: 'scala' },
  { label: 'Solidity', value: 'solidity' },
  { label: 'V', value: 'v' },
  { label: 'Vala', value: 'vala' },
  { label: 'Zig', value: 'zig' },
]

export const frontendSkills = [
  { label: 'Alpinejs', value: 'alpinejs' },
  { label: 'Angular', value: 'angular' },
  { label: 'Astro', value: 'astro' },
  { label: 'D3', value: 'd3' },
  { label: 'Electron.js', value: 'electron' },
  { label: 'Ember.js', value: 'ember' },
  { label: 'Emotion', value: 'emotion' },
  { label: 'jQuery', value: 'jquery' },
  { label: 'Ktor', value: 'ktor' },
  { label: 'Material UI(MUI)', value: 'materialui' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Nuxt.js', value: 'nuxtjs' },
  { label: 'Pug', value: 'pug' },
  { label: 'React', value: 'react' },
  { label: 'Redux', value: 'redux' },
  { label: 'Regex', value: 'regex' },
  { label: 'Remix', value: 'remix' },
  { label: 'Rocket', value: 'rocket' },
  { label: 'SASS', value: 'sass' },
  { label: 'styled-components', value: 'styledcomponents' },
  { label: 'SolidJS', value: 'solidjs' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'SVG', value: 'svg' },
  { label: 'Tailwind', value: 'tailwind' },
  { label: 'Tauri', value: 'tauri' },
  { label: 'Three.js', value: 'threejs' },
  { label: 'Vue.js', value: 'vue' },
  { label: 'Windi CSS', value: 'windicss' },
]

export const backendSkills = [
  { label: 'Actix', value: 'actix' }, // rustのフレームワーク
  { label: 'Ableton', value: 'ableton' },
  { label: 'Adonis', value: 'adonis' },
  { label: 'Deno', value: 'deno' },
  { label: 'Django', value: 'django' },
  { label: 'Express', value: 'express' },
  { label: 'Fastapi', value: 'fastapi' },
  { label: 'Flask', value: 'flask' },
  { label: 'Gulp.js', value: 'gulp' },
  { label: 'Laravel', value: 'laravel' },
  { label: 'NestJS', value: 'nestjs' },
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Ruby on Rails', value: 'rails' },
  { label: 'Spring', value: 'spring' },
  { label: 'Symfony', value: 'symfony' },
]

export const DBSkills = [
  { label: 'Cassandra', value: 'cassandra' },
  { label: 'Dynamodb', value: 'dynamodb' },
  { label: 'Firebase', value: 'firebase' },
  { label: 'Mongodb', value: 'mongodb' },
  { label: 'MySQL', value: 'mysql' },
  { label: 'Mongodb', value: 'mongodb' },
  { label: 'PlanetScale', value: 'planetscale' },
  { label: 'Postgres', value: 'postgres' },
  { label: 'Sqlite', value: 'sqlite' },
  { label: 'Supabase', value: 'supabase' },
]

export const otherSkills = [
  { label: 'Ableton', value: 'ableton' },
  { label: 'Activitypub', value: 'activitypub' },
  { label: 'Androidstudio', value: 'androidstudio' },
  { label: 'Ansible', value: 'ansible' },
  { label: 'Apollo', value: 'apollo' },
  { label: 'Appwrite', value: 'appwrite' },
  { label: 'Arduino', value: 'arduino' },
  { label: 'Atom', value: 'atom' }, // テキストエディタ
  { label: 'AWS', value: 'aws' },
  { label: 'Azul', value: 'azul' },
  { label: 'Azure', value: 'azure' },
  { label: 'Babel', value: 'babel' },
  { label: 'Bash', value: 'bash' },
  { label: 'Bevy', value: 'bevy' }, // Rustのゲームエンジン
  { label: 'Blender', value: 'blender' },
  { label: 'Bootstrap', value: 'bootstrap' },
  { label: 'Bsd', value: 'bsd' },
  { label: 'Cloudflare', value: 'cloudflare' },
  { label: 'Cmake', value: 'cmake' },
  { label: 'Codepen', value: 'codepen' },
  { label: 'Docker', value: 'docker' },
  { label: '.NET', value: 'dotnet' },
  { label: 'Eclipse', value: 'eclipse' },
  { label: 'Emacs', value: 'emacs' },
  { label: 'Figma', value: 'figma' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'GCP', value: 'gcp' },
  { label: 'Git', value: 'git' },
  { label: 'GitHub', value: 'github' },
  { label: 'Github Actions', value: 'githubactions' },
  { label: 'Github Lab', value: 'gitlab' },
  { label: 'Gherkin', value: 'gherkin' },
  { label: 'Gradle', value: 'gradle' },
  { label: 'Godot', value: 'godot' },
  { label: 'Grafana', value: 'grafana' },
  { label: 'Graphql', value: 'graphql' },
  { label: 'GTK', value: 'gtk' },
  { label: 'Haskell', value: 'haskell' },
  { label: 'Haxeflixel', value: 'haxeflixel' },
  { label: 'Heroku', value: 'heroku' },
  { label: 'Hibernate', value: 'hibernate' },
  { label: 'IDEA', value: 'idea' },
  { label: 'IPFS', value: 'ipfs' },
  { label: 'Jenkins', value: 'jenkins' },
  { label: 'Jest', value: 'jest' },
  { label: 'Kafka', value: 'kafka' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'Linux', value: 'linux' },
  { label: 'Markdown', value: 'md' },
  { label: 'MATLAB', value: 'matlab' },
  { label: 'Maven', value: 'maven' },
  { label: 'Neovim', value: 'neovim' },
  { label: 'Netlify', value: 'netlify' },
  { label: 'Nginx', value: 'nginx' },
  { label: 'OpenShift', value: 'openshift' },
  { label: 'OpenStack', value: 'openstack' },
  { label: 'Plan9', value: 'plan9' },
  { label: 'Postman', value: 'postman' },
  { label: 'Powershell', value: 'powershell' },
  { label: 'Prometheus', value: 'prometheus' },
  { label: 'PyTorch', value: 'pytorch' },
  { label: 'Qt', value: 'qt' },
  { label: 'Rabbitmq', value: 'rabbitmq' },
  { label: 'Raspberrypi', value: 'raspberrypi' },
  { label: 'Reactivex', value: 'reactivex' },
  { label: 'Replit', value: 'replit' },
  { label: 'Rollupjs', value: 'rollupjs' },
  { label: 'ROS', value: 'ros' },
  { label: 'Stackoverflow', value: 'stackoverflow' },
  { label: 'Selenium', value: 'selenium' },
  { label: 'Sentry', value: 'sentry' },
  { label: 'Sequelize', value: 'sequelize' },
  { label: 'Sketchup', value: 'sketchup' },
  { label: 'Swift', value: 'swift' },
  { label: 'Tensorflow', value: 'tensorflow' },
  { label: 'Unity', value: 'unity' },
  { label: 'Unreal', value: 'unreal' },
  { label: 'Vercel', value: 'vercel' },
  { label: 'Vim', value: 'vim' },
  { label: 'Visual Studio', value: 'visualstudio' },
  { label: 'vite', value: 'vite' },
  { label: 'VScode', value: 'vscode' },
  { label: 'WebAssembly', value: 'wasm' },
  { label: 'Webflow', value: 'webflow' },
  { label: 'Webpack', value: 'webpack' },
  { label: 'Wordpress', value: 'wordpress' },
]
